spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      chat:
        options:
          model: ${spring.ai.openai.chat.options.model}
        base-url: ${spring.ai.openai.chat.base-url}

prompt: ${prompt}

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

myapp:
  api-url: ${myapp.api-url}
  local-url: ${myapp.local-url}

jwt:
  secret: ${jwt.secret}

token:
  expire:
    time:
      access: ${token.expire.time.access}

oauth:
  kakao:
    client-id: ${oauth.kakao.client-id}
    redirect-uri: ${oauth.kakao.redirect-uri}
    id-token-url: ${oauth.kakao.id-token-url}
